---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/works
  label: works
  create: documents
  match: "**/*"
  new_doc_ext: mdx
  templates:
  - blog-post
- type: directory
  path: content/blog
  label: blog
  create: documents
  match: "**/*"
  new_doc_ext: mdx
  templates:
  - blog-post
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - GATSBY_GITHUB_PERSONAL_ACCESS_TOKEN=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
  preview_output_directory: public
  install_dependencies_command: yarn install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn dev
