---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/works
  label: works
  create: documents
  match: "**/*"
  new_doc_ext: mdx
  templates:
  - blog-post
- type: directory
  path: content/blog
  label: blog
  create: documents
  match: "**/*"
  new_doc_ext: mdx
  templates:
  - blog-post
upload_dir: media
public_path: https://res.cloudinary.com/dso4npatn/image/upload
front_matter_path: https://res.cloudinary.com/dso4npatn/image/upload
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:16
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
